-- Generado por Oracle SQL Developer Data Modeler 4.1.5.907
--   en:        2016-12-26 15:04:13 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP
  TABLE DEBT_T900_NIVEL_SISTEMA CASCADE CONSTRAINTS ;

DROP
  TABLE DEBT_T901_NIVEL_PROCEDIMIENTO CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T001_ENTIDAD CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T002_USUARIO CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T003_INVENTARIO CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T004_GEOMETRIA CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T005_CONTAMINANTE CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T006_FUENTE CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T007_INVENTARIOFUENTE CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T008_METODOEMISION CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T009_CATEGEMISION CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T010_CATEGCOMBUSTIBLE CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T011_UNIDADMEDIDA CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T012_UNIDADMEDIDAFACTOR CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T013_CATEGCONTAMINA CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T014_ADJUNTO CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T015_MENU CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T016_INVENTCONTAMINA CASCADE CONSTRAINTS ;

DROP
  TABLE IVET_T017_CATGEMIS_CIIU CASCADE CONSTRAINTS ;

DROP
  TABLE PART_T101_CATEGORIA CASCADE CONSTRAINTS ;

DROP
  TABLE PART_T102_LISTA CASCADE CONSTRAINTS ;

DROP
  TABLE PART_T105_DIVIPOLA CASCADE CONSTRAINTS ;

DROP
  TABLE PART_T108_CODIGOCIIU CASCADE CONSTRAINTS ;

DROP
  TABLE SIST_T996_AUDITORIA CASCADE CONSTRAINTS ;

DROP
  TABLE SIST_T997_MENSAJE_DEBUG CASCADE CONSTRAINTS ;

DROP
  TABLE SIST_T998_EXCEPCION CASCADE CONSTRAINTS ;

DROP
  TABLE SIST_T999_MENSAJE_RESPUESTA CASCADE CONSTRAINTS ;

DROP
  SEQUENCE T001_ENTIDAD_SEQ ;

DROP
  SEQUENCE T002_USUARIO_SEQ ;

DROP
  SEQUENCE T003_INVENTARIO_SEQ ;

DROP
  SEQUENCE T004_GEOMETRIA_SEQ ;

DROP
  SEQUENCE T005_CONTAMINANTE_SEQ ;

DROP
  SEQUENCE T006_FUENTE_SEQ ;

DROP
  SEQUENCE T007_INVENTARIOFUENTE_SEQ ;

DROP
  SEQUENCE T008_METODOEMISION_SEQ ;

DROP
  SEQUENCE T009_CATEGEMISION_SEQ ;

DROP
  SEQUENCE T010_CATEGCOMBUSTIBLE_SEQ ;

DROP
  SEQUENCE T011_UNIDADMEDIDA_SEQ ;

DROP
  SEQUENCE T012_UNIDADMEDIDAFACTOR_SEQ ;

DROP
  SEQUENCE T013_CATEGCONTAMINA_SEQ ;

DROP
  SEQUENCE T014_ADJUNTO_SEQ ;

DROP
  SEQUENCE T015_MENU_SEQ ;

DROP
  SEQUENCE T016_INVENTCONTAMINA_SEQ ;

DROP
  SEQUENCE T017_CATGEMIS_CIIU_SEQ ;

DROP
  SEQUENCE T101_CATEGORIA_SEQ ;

DROP
  SEQUENCE T102_LISTA_SEQ ;

DROP
  SEQUENCE T105_DIVIPOLA_SEQ ;

DROP
  SEQUENCE T108_CODIGOCIIU_SEQ ;

DROP
  SEQUENCE T900_NIVEL_SISTEMA_SEQ ;

DROP
  SEQUENCE T901_NIVEL_PROCEDIMIENTO_SEQ ;

DROP
  SEQUENCE T996_AUDITORIA_SEQ ;

DROP
  SEQUENCE T997_MENSAJE_DEBUG_SEQ ;

DROP
  SEQUENCE T998_EXCEPCION_SEQ ;

DROP
  SEQUENCE T999_MENSAJE_RESPUESTA_SEQ ;

CREATE SEQUENCE T001_ENTIDAD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T002_USUARIO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T003_INVENTARIO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T004_GEOMETRIA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T005_CONTAMINANTE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T006_FUENTE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T007_INVENTARIOFUENTE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T008_METODOEMISION_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T009_CATEGEMISION_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T010_CATEGCOMBUSTIBLE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T011_UNIDADMEDIDA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T012_UNIDADMEDIDAFACTOR_SEQ START WITH 1 INCREMENT BY 1
  MAXVALUE 9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T013_CATEGCONTAMINA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T014_ADJUNTO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T015_MENU_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T016_INVENTCONTAMINA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T017_CATGEMIS_CIIU_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T101_CATEGORIA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T102_LISTA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T105_DIVIPOLA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999
  MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T108_CODIGOCIIU_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T900_NIVEL_SISTEMA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T901_NIVEL_PROCEDIMIENTO_SEQ START WITH 1 INCREMENT BY 1
  MAXVALUE 9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T996_AUDITORIA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  999999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T997_MENSAJE_DEBUG_SEQ START WITH 121 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T998_EXCEPCION_SEQ START WITH 41 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE T999_MENSAJE_RESPUESTA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE
  9999999 MINVALUE 1 CACHE 20 ;

CREATE
  TABLE DEBT_T900_NIVEL_SISTEMA
  (
    A900CODIGO              NUMBER (7) NOT NULL ,
    A900DESCRIPCION         VARCHAR2 (50) ,
    A900ESTADOREGISTRO      CHAR (1) ,
    A900FECHACREACION       DATE ,
    A900FECHAMODIFICACION   DATE ,
    A900USUARIOCREACION     NUMBER ,
    A900USUARIOMODIFICACION NUMBER
  ) ;
ALTER TABLE DEBT_T900_NIVEL_SISTEMA ADD CONSTRAINT CK_A900ESTADOREGISTRO CHECK
( A900ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE DEBT_T900_NIVEL_SISTEMA
IS
  'NIVEL DE DEPURACION DEL SISTEMA' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900CODIGO
IS
  'IDENTIFICACION DEL REGISTRO' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900DESCRIPCION
IS
  'DESCRIPCION DEL NIVEL' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900ESTADOREGISTRO
IS
  'ESTADO DEL REGISTRO' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900FECHACREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900FECHAMODIFICACION
IS
  'FECHA DE LA ULTIMA MODIFICACION' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900USUARIOCREACION
IS
  'ID DEL USUARIO CREADOR' ;
  COMMENT ON COLUMN DEBT_T900_NIVEL_SISTEMA.A900USUARIOMODIFICACION
IS
  'ID DEL ULTIMO USUARIO QUE MODIFICO' ;
ALTER TABLE DEBT_T900_NIVEL_SISTEMA ADD CONSTRAINT PK_T900 PRIMARY KEY (
A900CODIGO ) ;


CREATE
  TABLE DEBT_T901_NIVEL_PROCEDIMIENTO
  (
    A901CODIGO              NUMBER (7) NOT NULL ,
    A901PAQUETE             VARCHAR2 (100) ,
    A901PROCEDIMIENTO       VARCHAR2 (100) ,
    A901ESTADOREGISTRO      CHAR (1) ,
    A901FECHACREACION       DATE ,
    A901FECHAMODIFICACION   DATE ,
    A901USUARIOCREACION     NUMBER ,
    A901USUARIOMODIFICACION NUMBER
  ) ;
ALTER TABLE DEBT_T901_NIVEL_PROCEDIMIENTO ADD CONSTRAINT CK_A901ESTADOREGISTRO
CHECK ( A901ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE DEBT_T901_NIVEL_PROCEDIMIENTO
IS
  'NIVEL DE DEPURACION POR PROCEDIMIENTO' ;
ALTER TABLE DEBT_T901_NIVEL_PROCEDIMIENTO ADD CONSTRAINT PK_T901_1 PRIMARY KEY
( A901CODIGO ) ;
ALTER TABLE DEBT_T901_NIVEL_PROCEDIMIENTO ADD CONSTRAINT PK_T901_2 UNIQUE (
A901PAQUETE , A901PROCEDIMIENTO ) ;


CREATE
  TABLE IVET_T001_ENTIDAD
  (
    A001CODIGO              NUMBER (7) NOT NULL ,
    A001SIGLAAUTAMB         VARCHAR2 (50) NOT NULL ,
    A001NOMBREAUTAMB        VARCHAR2 (200) NOT NULL ,
    A001CODDIVIPOLA         NUMBER (7) NOT NULL ,
    A001ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A001FECHACREACION       DATE ,
    A001FECHAMODIFICACION   DATE ,
    A001USUARIOCREACION     NUMBER (7) NOT NULL ,
    A001USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T001_ENTIDAD ADD CONSTRAINT CK_A001ESTADOREGISTRO CHECK (
A001ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T001_ENTIDAD
IS
  'Autoridades ambientales' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001CODIGO
IS
  'Llave primaria (Autoridad_Ambiental)' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001SIGLAAUTAMB
IS
  'SIGLA que Identifica la Autoridad Ambiental ' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001NOMBREAUTAMB
IS
  'Nombre completo de la Autoridad Ambiental ' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001CODDIVIPOLA
IS
  'Identificador divipola municipios' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T001_ENTIDAD.A001USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T001_ENTIDAD ADD CONSTRAINT PK_T001 PRIMARY KEY ( A001CODIGO )
;


CREATE
  TABLE IVET_T002_USUARIO
  (
    A002CODIGO              NUMBER (7) NOT NULL ,
    A002NOMBRE              VARCHAR2 (50) NOT NULL ,
    A002APELLIDO            VARCHAR2 (100) NOT NULL ,
    A002IDTIPODOCUMENTO     NUMBER (7) NOT NULL ,
    A002DOCUMENTO           VARCHAR2 (10) NOT NULL ,
    A002EXPEDIDOEN          VARCHAR2 (80) ,
    A002DIRECCIONCORRESP    VARCHAR2 (50) NOT NULL ,
    A002LOCALIZACION        NUMBER (7) NOT NULL ,
    A002CORREOELECTRONICO   VARCHAR2 (40) NOT NULL ,
    A002TELEFONO            VARCHAR2 (20) ,
    A002CELULAR             VARCHAR2 (20) ,
    A002PRIMERINGRESO       CHAR (2) ,
    A002USUARIO             VARCHAR2 (15) NOT NULL ,
    A002CONTRASENA          VARCHAR2 (15) NOT NULL ,
    A002TIPOUSUARIO         NUMBER (7) NOT NULL ,
    A002AUTORIDADAMBIENTAL  NUMBER (7) NOT NULL ,
    A002MENU                NUMBER (7) ,
    A002ESTADOUSUARIO       CHAR (1) NOT NULL ,
    A002ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A002FECHACREACION       DATE ,
    A002FECHAMODIFICACION   DATE ,
    A002USUARIOCREACION     NUMBER (7) NOT NULL ,
    A002USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT CK_A002PRIMERINGRESO CHECK (
A002PRIMERINGRESO IN ('NO', 'SI')) ;
ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT CK_A002ESTADOUSUARIO CHECK (
A002ESTADOUSUARIO IN ('A', 'I')) ;
ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT CK_A002ESTADOREGISTRO CHECK (
A002ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T002_USUARIO
IS
  'Usuarios del sistema' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002CODIGO
IS
  'Llave primaria (Usuario)' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002NOMBRE
IS
  'Nombre del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002APELLIDO
IS
  'Apellidos del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002IDTIPODOCUMENTO
IS
  'Determina los tipos de documento del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002DOCUMENTO
IS
  'Numero del documento de identificaciOn' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002EXPEDIDOEN
IS
  'Lugar de expedición del documento' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002DIRECCIONCORRESP
IS
  'DirecciOn correspondencia del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002LOCALIZACION
IS
  'Identificador del lugar de residencia del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002CORREOELECTRONICO
IS
  'Correo electronico' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002TELEFONO
IS
  'Teléfono usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002CELULAR
IS
  'Celular usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002PRIMERINGRESO
IS
  'Saber si es el primer logueo del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002USUARIO
IS
  'Usuario o alias para acceder a la aplicaciOn' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002CONTRASENA
IS
  'Contraseña para acceder a la aplicaciOn' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002TIPOUSUARIO
IS
  'Identifica el tipo de usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002AUTORIDADAMBIENTAL
IS
  'Identifica la Autoridad Ambiental a la que pertenece el usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002MENU
IS
  'Menu al que tiene acceso el usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002ESTADOUSUARIO
IS
  'Estado del usuario' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T002_USUARIO.A002USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT PK_T002 PRIMARY KEY ( A002CODIGO )
;
ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT UK_A002DOCUMENTO UNIQUE (
A002DOCUMENTO ) ;


CREATE
  TABLE IVET_T003_INVENTARIO
  (
    A003CODIGO                 NUMBER (7) NOT NULL ,
    A003OBJETO                 VARCHAR2 (2000) NOT NULL ,
    A003FECHA_INICIAL          DATE ,
    A003FECHA_FINAL            DATE ,
    A003ESTADO_INVENTARIO      NUMBER (7) NOT NULL ,
    A003OBS_RECHAZO            VARCHAR2 (300) ,
    A003IDDIVIPOLA             NUMBER (7) NOT NULL ,
    A003DESCRIPCION_TERRITORIO VARCHAR2 (500) ,
    A003IDUSUARIOREGISTRO      NUMBER (7) NOT NULL ,
    A003ESTADOREGISTRO         CHAR (1) NOT NULL ,
    A003FECHACREACION          DATE ,
    A003FECHAMODIFICACION      DATE ,
    A003USUARIOCREACION        NUMBER (7) NOT NULL ,
    A003USUARIOMODIFICACION    NUMBER (7)
  ) ;
ALTER TABLE IVET_T003_INVENTARIO ADD CONSTRAINT CK_A003ESTADOREGISTRO CHECK (
A003ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T003_INVENTARIO
IS
  'Inventario Registrado' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003CODIGO
IS
  'Llave primaria (Inventario)' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003OBJETO
IS
  'DescripciOn del inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003FECHA_INICIAL
IS
  'Fecha de inicio del inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003FECHA_FINAL
IS
  'Fecha estimada de finalizaciOn del inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003ESTADO_INVENTARIO
IS
  'Identifica el estado en que se encuentra el inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003OBS_RECHAZO
IS
  'Descripción de laa razón del rechazo (de existir)' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003IDDIVIPOLA
IS
  'Código DIVIPOLA del Municipio donde se desarrolla el Inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003DESCRIPCION_TERRITORIO
IS
  'DescripciOn del territorio donde se realiza el inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003IDUSUARIOREGISTRO
IS
  'Identificador del usuario que registra el inventario' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T003_INVENTARIO.A003USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T003_INVENTARIO ADD CONSTRAINT PK_T003 PRIMARY KEY (
A003CODIGO ) ;


CREATE
  TABLE IVET_T004_GEOMETRIA
  (
    A004CODIGO NUMBER (7) NOT NULL ,
    A004GEOMETRIA CLOB ,
    A004IDINVENTARIO        NUMBER (7) NOT NULL ,
    A004ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A004FECHACREACION       DATE ,
    A004FECHAMODIFICACION   DATE ,
    A004USUARIOCREACION     NUMBER (7) NOT NULL ,
    A004USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T004_GEOMETRIA ADD CONSTRAINT CK_A004ESTADOREGISTRO CHECK (
A004ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T004_GEOMETRIA
IS
  'Geometría del sitio asociado al inventario ' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004CODIGO
IS
  'Llave primaria (Geometria)' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004GEOMETRIA
IS
  'Geometria' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004IDINVENTARIO
IS
  'Identificador del Inventario asociado' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T004_GEOMETRIA.A004USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T004_GEOMETRIA ADD CONSTRAINT PK_T004 PRIMARY KEY ( A004CODIGO
) ;


CREATE
  TABLE IVET_T005_CONTAMINANTE
  (
    A005CODIGO              NUMBER (7) NOT NULL ,
    A005CONTAMINANTE        VARCHAR2 (200) NOT NULL ,
    A005ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A005FECHACREACION       DATE ,
    A005FECHAMODIFICACION   DATE ,
    A005USUARIOCREACION     NUMBER (7) NOT NULL ,
    A005USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T005_CONTAMINANTE ADD CONSTRAINT CK_A005ESTADOREGISTRO CHECK (
A005ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T005_CONTAMINANTE
IS
  'Contaminantes asociados al inventario' ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005CODIGO
IS
  'Llave primaria (Contaminante)' ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005CONTAMINANTE
IS
  'DescripciOn del contaminante' ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T005_CONTAMINANTE.A005USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T005_CONTAMINANTE ADD CONSTRAINT PK_T005 PRIMARY KEY (
A005CODIGO ) ;


CREATE
  TABLE IVET_T006_FUENTE
  (
    A006CODIGO              NUMBER (7) NOT NULL ,
    A006FUENTE              VARCHAR2 (100) NOT NULL ,
    A006ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A006FECHACREACION       DATE ,
    A006FECHAMODIFICACION   DATE ,
    A006USUARIOCREACION     NUMBER (7) NOT NULL ,
    A006USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T006_FUENTE ADD CONSTRAINT CK_A006ESTADOREGISTRO CHECK (
A006ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T006_FUENTE
IS
  'Fuentes de emisiOn' ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006CODIGO
IS
  'Llave primaria (Fuente)' ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006FUENTE
IS
  'DescrripciOn de la fuente' ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T006_FUENTE.A006USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T006_FUENTE ADD CONSTRAINT PK_T006 PRIMARY KEY ( A006CODIGO )
;


CREATE
  TABLE IVET_T007_INVENTARIOFUENTE
  (
    A007CODIGO              NUMBER (7) NOT NULL ,
    A007IDINVENTARIO        NUMBER (7) NOT NULL ,
    A007IDFUENTE            NUMBER (7) NOT NULL ,
    A007ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A007FECHACREACION       DATE ,
    A007FECHAMODIFICACION   DATE ,
    A007USUARIOCREACION     NUMBER (7) NOT NULL ,
    A007USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T007_INVENTARIOFUENTE ADD CONSTRAINT CK_A007ESTADOREGISTRO
CHECK ( A007ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T007_INVENTARIOFUENTE
IS
  'Fuentes asociadas al inventario' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007CODIGO
IS
  'Llave primaria (Inventario_Fuente)' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007IDINVENTARIO
IS
  'Identificador del Inventario' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007IDFUENTE
IS
  'Identificador de la Fuente' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T007_INVENTARIOFUENTE.A007USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T007_INVENTARIOFUENTE ADD CONSTRAINT PK_T007 PRIMARY KEY (
A007CODIGO ) ;


CREATE
  TABLE IVET_T008_METODOEMISION
  (
    A008CODIGO              NUMBER (7) NOT NULL ,
    A008METODODETEMISION    VARCHAR2 (800) NOT NULL ,
    A008ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A008FECHACREACION       DATE ,
    A008FECHAMODIFICACION   DATE ,
    A008USUARIOCREACION     NUMBER (7) NOT NULL ,
    A008USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T008_METODOEMISION ADD CONSTRAINT CK_A008ESTADOREGISTRO CHECK
( A008ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T008_METODOEMISION
IS
  'Metodos de determinaciOn de emisiones' ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008CODIGO
IS
  'Llave primaria (Metodo_Determinacion)' ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008METODODETEMISION
IS
  'Método con el que se determinO la emisiOn.' ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T008_METODOEMISION.A008USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T008_METODOEMISION ADD CONSTRAINT PK_T008 PRIMARY KEY (
A008CODIGO ) ;


CREATE
  TABLE IVET_T009_CATEGEMISION
  (
    A009CODIGO              NUMBER (7) NOT NULL ,
    A009NOMCATEMISION       VARCHAR2 (120) NOT NULL ,
    A009DESCCATEMISION      VARCHAR2 (120) ,
    A009IDTIPOCATEMISION    NUMBER (7) NOT NULL ,
    A009IDINVENTARIO        NUMBER (7) NOT NULL ,
    A009IDTIPOCOMBUSTIBLE   NUMBER (7) NOT NULL ,
    A009CILINDRAJE          NUMBER ,
    A009ANIOMODELO          NUMBER (4) ,
    A009NROFUENTES          NUMBER (6) NOT NULL ,
    A009DETMETODFUENTES     VARCHAR2 (500) ,
    A009IDMETODOEMISION     NUMBER (7) NOT NULL ,
    A009OBSERVACION         VARCHAR2 (2000) ,
    A009TOTALEMISION        NUMBER ,
    A009ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A009FECHACREACION       DATE ,
    A009FECHAMODIFICACION   DATE ,
    A009USUARIOCREACION     NUMBER (7) NOT NULL ,
    A009USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T009_CATEGEMISION ADD CONSTRAINT CK_A009ESTADOREGISTRO CHECK (
A009ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T009_CATEGEMISION
IS
  'Informacion de la categoría relacionada en el inventario' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009CODIGO
IS
  'Llave primaria (Inventario_Categoría)' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009NOMCATEMISION
IS
  'Nombre de la Categoria de Emision asociada al Inventario' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009DESCCATEMISION
IS
  'Descripcion de la Categoria de Emision asociada al Inventario' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009IDTIPOCATEMISION
IS
  'Identificador del tipo de Categoría de emsion' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009IDINVENTARIO
IS
  'Identificador del Inventario' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009IDTIPOCOMBUSTIBLE
IS
  'Identificador del tipo de combustible' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009CILINDRAJE
IS
  'Cilindraje (aplica para fuentes moviles)' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009ANIOMODELO
IS
  'Año / Modelo (aplica para fuentes moviles)' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009NROFUENTES
IS
  'Número estimado de fuentes de emision' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009DETMETODFUENTES
IS
  'Detalle del metodo de estimacion de fuentes de emision' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009IDMETODOEMISION
IS
  'Método con el que se determinO la emisiOn' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009OBSERVACION
IS
  'ObservaciOn de la categoría' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009TOTALEMISION
IS
  'Sumatoria de “EmisiOn total de todos los contaminantes” ' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T009_CATEGEMISION.A009USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T009_CATEGEMISION ADD CONSTRAINT PK_T009 PRIMARY KEY (
A009CODIGO ) ;


CREATE
  TABLE IVET_T010_CATEGCOMBUSTIBLE
  (
    A010CODIGO                NUMBER (7) NOT NULL ,
    A010CODCATEMISION NUMBER (7) NOT NULL ,
    A010IDTIPOCOMBUSTIBLE     NUMBER (7) NOT NULL ,
    A010ESTADOREGISTRO        CHAR (1) NOT NULL ,
    A010FECHACREACION         DATE ,
    A010FECHAMODIFICACION     DATE ,
    A010USUARIOCREACION       NUMBER (7) NOT NULL ,
    A010USUARIOMODIFICACION   NUMBER (7)
  ) ;
ALTER TABLE IVET_T010_CATEGCOMBUSTIBLE ADD CONSTRAINT CK_A010ESTADOREGISTRO
CHECK ( A010ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T010_CATEGCOMBUSTIBLE
IS
  'Informacion de los combustibles relacionada con los combustibes del inventario'
  ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010CODIGO
IS
  'Llave primaria (Categoría_Combustible)' ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010CODCATEMISION
IS
  'Identificador inventario-categoría' ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010IDTIPOCOMBUSTIBLE
IS
  'Identificador del tipo de combustible' ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T010_CATEGCOMBUSTIBLE.A010USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T010_CATEGCOMBUSTIBLE ADD CONSTRAINT PK_T010 PRIMARY KEY (
A010CODIGO ) ;


CREATE
  TABLE IVET_T011_UNIDADMEDIDA
  (
    A011CODIGO              NUMBER (7) NOT NULL ,
    A011UNIDADMEDIDA        NUMBER ,
    A011ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A011FECHACREACION       DATE ,
    A011FECHAMODIFICACION   DATE ,
    A011USUARIOCREACION     NUMBER (7) NOT NULL ,
    A011USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T011_UNIDADMEDIDA ADD CONSTRAINT CK_A011ESTADOREGISTRO CHECK (
A011ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T011_UNIDADMEDIDA
IS
  'Unidades de Medida del factor de actividad' ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011CODIGO
IS
  'Llave primaria (Unidad_Medida)' ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011UNIDADMEDIDA
IS
  'DescripciOn de la unidad de medida' ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T011_UNIDADMEDIDA.A011USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T011_UNIDADMEDIDA ADD CONSTRAINT PK_T011 PRIMARY KEY (
A011CODIGO ) ;


CREATE
  TABLE IVET_T012_UNIDADMEDIDAFACTOR
  (
    A012CODIGO              NUMBER (7) NOT NULL ,
    A012UNIDADMEDIDA        VARCHAR2 (50) NOT NULL ,
    A012ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A012FECHACREACION       DATE ,
    A012FECHAMODIFICACION   DATE ,
    A012USUARIOCREACION     NUMBER (7) NOT NULL ,
    A012USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T012_UNIDADMEDIDAFACTOR ADD CONSTRAINT CK_A012ESTADOREGISTRO
CHECK ( A012ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T012_UNIDADMEDIDAFACTOR
IS
  'Unidad de Medida por Factor de EmisiOn' ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012CODIGO
IS
  'Llave primaria (Unidad_Medida_Factor)' ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012UNIDADMEDIDA
IS
  'DescripciOn de la unidad de medida del factor de emisiOn' ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T012_UNIDADMEDIDAFACTOR.A012USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T012_UNIDADMEDIDAFACTOR ADD CONSTRAINT PK_T012 PRIMARY KEY (
A012CODIGO ) ;


CREATE
  TABLE IVET_T013_CATEGCONTAMINA
  (
    A013CODIGO              NUMBER (7) NOT NULL ,
    A013IDCATEGORIAEMISION  NUMBER (7) NOT NULL ,
    A013IDCONTAMINANTE      NUMBER (7) NOT NULL ,
    A013VALORCONTAMINANTE   NUMBER (20,5) ,
    A013FACTORACTIVIDAD     NUMBER (6) NOT NULL ,
    A013UNDMEDFACTORACTIV   NUMBER (7) ,
    A013FTEMETDFACTORACTIV  VARCHAR2 (800) NOT NULL ,
    A013FACTOREMISION       NUMBER (20,5) ,
    A013UNDMEDFACTOREMIS    NUMBER (7) NOT NULL ,
    A013FTEMETDFACTOREMIS   VARCHAR2 (200) ,
    A013EMISIONTOTAL        NUMBER (20,5) ,
    A013ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A013FECHACREACION       DATE ,
    A013FECHAMODIFICACION   DATE ,
    A013USUARIOCREACION     NUMBER (7) NOT NULL ,
    A013USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T013_CATEGCONTAMINA ADD CONSTRAINT CK_A013ESTADOREGISTRO CHECK
( A013ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T013_CATEGCONTAMINA
IS
  'Contaminantes asociados a las categorías' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013CODIGO
IS
  'Llave primaria (Categoria_Contaminante)' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013IDCATEGORIAEMISION
IS
  'Identificador de la categoria de emision' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013IDCONTAMINANTE
IS
  'Identificador del contaminante' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013VALORCONTAMINANTE
IS
  'Valor del contaminante' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013FACTORACTIVIDAD
IS
  'Factor de actividad' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013UNDMEDFACTORACTIV
IS
  'Unidad de medida del factor de actividad' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013FTEMETDFACTORACTIV
IS
  'Fuente o Método de estimaciOn del Factor de Actividad' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013FACTOREMISION
IS
  'Fuente o método de estimaciOn del Factor de Actividad por categoría por contaminante'
  ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013UNDMEDFACTOREMIS
IS
  'Unidad deMedida del Factor de Emision' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013FTEMETDFACTOREMIS
IS
  'Método de estimacion del factor de emision' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013EMISIONTOTAL
IS
  'Emision total =  
núm. fuentes* factor de emisiOn* factor de actividad ' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T013_CATEGCONTAMINA.A013USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T013_CATEGCONTAMINA ADD CONSTRAINT PK_T013 PRIMARY KEY (
A013CODIGO ) ;


CREATE
  TABLE IVET_T014_ADJUNTO
  (
    A014CODIGO              NUMBER (7) NOT NULL ,
    A014NOMBREADJUNTO       VARCHAR2 (7) NOT NULL ,
    A014RUTAADJUNTO         VARCHAR2 (200) NOT NULL ,
    A014IDINVENTARIO        NUMBER (7) NOT NULL ,
    A014ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A014FECHACREACION       DATE ,
    A014FECHAMODIFICACION   DATE ,
    A014USUARIOCREACION     NUMBER (7) NOT NULL ,
    A014USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T014_ADJUNTO ADD CONSTRAINT CK_A014ESTADOREGISTRO CHECK (
A014ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T014_ADJUNTO
IS
  'InformaciOn archivos adjuntos' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014CODIGO
IS
  'Llave primaria (Adjunto)' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014NOMBREADJUNTO
IS
  'Nombre del adjunto' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014RUTAADJUNTO
IS
  'Ruta del adjunto' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014IDINVENTARIO
IS
  'Identificador del Inventario asociado' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T014_ADJUNTO.A014USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T014_ADJUNTO ADD CONSTRAINT PK_T014 PRIMARY KEY ( A014CODIGO )
;


CREATE
  TABLE IVET_T015_MENU
  (
    A015CODIGO              NUMBER (7) NOT NULL ,
    A015ROLMENU             VARCHAR2 (50) NOT NULL ,
    A015MENUPADRE           VARCHAR2 (50) NOT NULL ,
    A015MENUHIJO            VARCHAR2 (50) NOT NULL ,
    A015ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A015FECHACREACION       DATE ,
    A015FECHAMODIFICACION   DATE ,
    A015USUARIOCREACION     NUMBER (7) NOT NULL ,
    A015USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T015_MENU ADD CONSTRAINT CK_A015ESTADOREGISTRO CHECK (
A015ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T015_MENU
IS
  'Menú usuarios' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015CODIGO
IS
  'Llave primaria (Menu)' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015ROLMENU
IS
  'Nombre del rol que utiliza el menú' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015MENUPADRE
IS
  'Nombre menu padre ' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015MENUHIJO
IS
  'Nombre Hijo' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T015_MENU.A015FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T015_MENU.A015USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T015_MENU ADD CONSTRAINT PK_T015 PRIMARY KEY ( A015CODIGO ) ;


CREATE
  TABLE IVET_T016_INVENTCONTAMINA
  (
    A016CODIGO              NUMBER (7) NOT NULL ,
    A016IDINVENTARIO        NUMBER (7) NOT NULL ,
    A016IDCONTAMINANTE      NUMBER (7) NOT NULL ,
    A016ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A016FECHACREACION       DATE ,
    A016FECHAMODIFICACION   DATE ,
    A016USUARIOCREACION     NUMBER (7) NOT NULL ,
    A016USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T016_INVENTCONTAMINA ADD CONSTRAINT CK_A016ESTADOREGISTRO
CHECK ( A016ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T016_INVENTCONTAMINA
IS
  'Contaminantes asociados al inventario' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016CODIGO
IS
  'Llave primaria (Inventario_Fuente)' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016IDINVENTARIO
IS
  'Identificador del Inventario' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016IDCONTAMINANTE
IS
  'Identificador del Contaminante' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T016_INVENTCONTAMINA.A016USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T016_INVENTCONTAMINA ADD CONSTRAINT PK_T016 PRIMARY KEY (
A016CODIGO ) ;


CREATE
  TABLE IVET_T017_CATGEMIS_CIIU
  (
    A017CODIGO              NUMBER (7) NOT NULL ,
    A017CODCATEMISION       NUMBER (7) NOT NULL ,
    A017IDCODCIIU           NUMBER (7) NOT NULL ,
    A017ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A017FECHACREACION       DATE ,
    A017FECHAMODIFICACION   DATE ,
    A017USUARIOCREACION     NUMBER (7) NOT NULL ,
    A017USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE IVET_T017_CATGEMIS_CIIU ADD CONSTRAINT CK_A017ESTADOREGISTRO CHECK
( A017ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE IVET_T017_CATGEMIS_CIIU
IS
  'Códigos CIIU asociados a la categoria' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017CODIGO
IS
  'Llave primaria (CatEmision_CIIU)' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017CODCATEMISION
IS
  'Identificador de la Categoria de Emision' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017IDCODCIIU
IS
  'Identificador del Codigo CIIU' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN IVET_T017_CATGEMIS_CIIU.A017USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE IVET_T017_CATGEMIS_CIIU ADD CONSTRAINT PK_T017 PRIMARY KEY (
A017CODIGO ) ;


CREATE
  TABLE PART_T101_CATEGORIA
  (
    A101CODIGO              NUMBER (7) NOT NULL ,
    A101NOMBRE              VARCHAR2 (200) NOT NULL ,
    A101ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A101FECHACREACION       DATE ,
    A101FECHAMODIFICACION   DATE ,
    A101USUARIOCREACION     NUMBER (7) NOT NULL ,
    A101USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE PART_T101_CATEGORIA ADD CONSTRAINT CK_A101ESTADOREGISTRO CHECK (
A101ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE PART_T101_CATEGORIA
IS
  'Parámetros del sistema' ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101CODIGO
IS
  'Llave primaria (Categoria)' ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101NOMBRE
IS
  'Nombre de la categoria' ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando es requerido ser borrado). '
  ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101FECHAMODIFICACION
IS
  'Fecha de la última modificaciOn del registro' ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro' ;
  COMMENT ON COLUMN PART_T101_CATEGORIA.A101USUARIOMODIFICACION
IS
  'Usuario que realiza la última modificaciOn del registro' ;
ALTER TABLE PART_T101_CATEGORIA ADD CONSTRAINT PK_T101 PRIMARY KEY ( A101CODIGO
) ;
ALTER TABLE PART_T101_CATEGORIA ADD CONSTRAINT UK_A101NOMBRE UNIQUE (
A101NOMBRE ) ;


CREATE
  TABLE PART_T102_LISTA
  (
    A102CODIGO              NUMBER (7) NOT NULL ,
    A102CATEGORIA           NUMBER (7) NOT NULL ,
    A102VALOR               VARCHAR2 (300) NOT NULL ,
    A102VALORCORTO          VARCHAR2 (30) ,
    A102ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A102FECHACREACION       DATE ,
    A102FECHAMODIFICACION   DATE ,
    A102USUARIOCREACION     NUMBER (7) NOT NULL ,
    A102USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE PART_T102_LISTA ADD CONSTRAINT CK_A102ESTADOREGISTRO CHECK (
A102ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE PART_T102_LISTA
IS
  'Lista por Parámetros del sistema' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102CODIGO
IS
  'Llave primaria (Lista)' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102CATEGORIA
IS
  'Nombre de la categoria' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102VALOR
IS
  'Nombre del parámetro' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102VALORCORTO
IS
  'Nombre corto del parámetro' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando es requerido ser borrado). '
  ;
  COMMENT ON COLUMN PART_T102_LISTA.A102FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102FECHAMODIFICACION
IS
  'Fecha de la última modificaciOn del registro' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro' ;
  COMMENT ON COLUMN PART_T102_LISTA.A102USUARIOMODIFICACION
IS
  'Usuario que realiza la última modificaciOn del registro' ;
ALTER TABLE PART_T102_LISTA ADD CONSTRAINT PK_T102 PRIMARY KEY ( A102CODIGO ) ;


CREATE
  TABLE PART_T105_DIVIPOLA
  (
    A105CODIGO              NUMBER (7) NOT NULL ,
    A105CODDIVIPOLA         VARCHAR2 (9) NOT NULL ,
    A105CODDIVIPOLADM       VARCHAR2 (5) NOT NULL ,
    A105CODPAIS             NUMBER (3) NOT NULL ,
    A105PAIS             VARCHAR2 (20) NOT NULL ,
    A105CODDEPARTAMENTO     NUMBER (3) NOT NULL ,
    A105DEPARTAMENTO     VARCHAR2 (30) NOT NULL ,
    A105CODMUNICIPIO         NUMBER (4) NOT NULL ,
    A105MUNICIPIO         VARCHAR2 (30) NOT NULL ,
    A105ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A105FECHACREACION       DATE ,
    A105FECHAMODIFICACION   DATE ,
    A105USUARIOCREACION     NUMBER (7) NOT NULL ,
    A105USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE PART_T105_DIVIPOLA ADD CONSTRAINT CK_A105ESTADOREGISTRO CHECK (
A105ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE PART_T105_DIVIPOLA
IS
  'COdigos Divipola' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105CODIGO
IS
  'Llave primaria (Divipola)' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105CODDIVIPOLA
IS
  'Codigo del país, departamento y  municipio (XXYYYZZZ)' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105CODDIVIPOLADM
IS
  'Codigo del departamento y  municipio (YYYZZZ)' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105CODPAIS
IS
  'Código del Pais' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105PAIS
IS
  'Nombre del Pais' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105CODDEPARTAMENTO
IS
  'Código del Departamento' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105DEPARTAMENTO
IS
  'Nombre del Departamento' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105CODMUNICIPIO
IS
  'Código del Municipio' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105MUNICIPIO
IS
  'Nombre del Municipio' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN PART_T105_DIVIPOLA.A105USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE PART_T105_DIVIPOLA ADD CONSTRAINT PK_T105 PRIMARY KEY ( A105CODIGO
) ;


CREATE
  TABLE PART_T108_CODIGOCIIU
  (
    A108CODIGO              NUMBER (7) NOT NULL ,
    A108CODIGOCIIU          NUMBER (5) NOT NULL ,
    A108DESCRIPCIONCIIU     VARCHAR2 (500) ,
    A108ESTADOREGISTRO      CHAR (1) NOT NULL ,
    A108FECHACREACION       DATE ,
    A108FECHAMODIFICACION   DATE ,
    A108USUARIOCREACION     NUMBER (7) NOT NULL ,
    A108USUARIOMODIFICACION NUMBER (7)
  ) ;
ALTER TABLE PART_T108_CODIGOCIIU ADD CONSTRAINT CK_A108ESTADOREGISTRO CHECK (
A108ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE PART_T108_CODIGOCIIU
IS
  'COdigos CIIU' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108CODIGO
IS
  'Llave primaria (Codigo_CIIU)' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108CODIGOCIIU
IS
  'COdigo de la actividad econOmica' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108DESCRIPCIONCIIU
IS
  'DescripciOn del cOdigo CIIU' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108ESTADOREGISTRO
IS
  'Indica si el registro esta activo A, o ha sido inactivado I (cuando se requerido ser borrado). '
  ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108FECHACREACION
IS
  'Fecha de creaciOn del registro' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108FECHAMODIFICACION
IS
  'Fecha de la ultima modificaciOn del registro' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108USUARIOCREACION
IS
  'Usuario que realiza la creaciOn del registro.' ;
  COMMENT ON COLUMN PART_T108_CODIGOCIIU.A108USUARIOMODIFICACION
IS
  'Usuario que realiza la ultima modificaciOn del registro. ' ;
ALTER TABLE PART_T108_CODIGOCIIU ADD CONSTRAINT PK_T108 PRIMARY KEY (
A108CODIGO ) ;


CREATE
  TABLE SIST_T996_AUDITORIA
  (
    A996CODIGO        NUMBER (9) NOT NULL ,
    A996FECHA         DATE ,
    A996IDOBJETO      NUMBER ,
    A996OBJETO        VARCHAR2 (100) ,
    A996OPERACION     VARCHAR2 (50) ,
    A996USUARIO       NUMBER ,
    A996PROCEDIMIENTO VARCHAR2 (200) ,
    A996PAQUETE       VARCHAR2 (200)
  ) ;
ALTER TABLE SIST_T996_AUDITORIA ADD CONSTRAINT CK_A996OPERACION CHECK (
A996OPERACION IN ('ACTUALIZAR', 'ELIMINAR', 'INSERTAR')) ;
COMMENT ON TABLE SIST_T996_AUDITORIA
IS
  'AUDITORIA DE LAS OPERACIONES REALIZADAS SOBRE LOS DATOS' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996CODIGO
IS
  'ID UNICA DEL REGISTRO' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996FECHA
IS
  'FECHA DE OPERACION' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996IDOBJETO
IS
  'NUMERO UNICO DEL OBJETO AFECTADO' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996OBJETO
IS
  'NOMBRE DEL OBJETO AFECTADO' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996OPERACION
IS
  'OPERACION REALIZADA: ELIMINAR, INSERTAR, ACTUALIZAR' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996USUARIO
IS
  'ID DEL USUARIO QUE REALIZO OPERACION' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996PROCEDIMIENTO
IS
  'NOMBRE DEL PROCEDIMIENTO' ;
  COMMENT ON COLUMN SIST_T996_AUDITORIA.A996PAQUETE
IS
  'NOMBRE DEL PAQUETE' ;
ALTER TABLE SIST_T996_AUDITORIA ADD CONSTRAINT PK_T996 PRIMARY KEY ( A996CODIGO
) ;


CREATE
  TABLE SIST_T997_MENSAJE_DEBUG
  (
    A997CODIGO         NUMBER NOT NULL ,
    A997FECHAOPERACION DATE ,
    A997USUARIO        NUMBER ,
    A997PAQUETE        VARCHAR2 (30) ,
    A997PROCEDIMIENTO  VARCHAR2 (30) ,
    A997DESCRIPCION    VARCHAR2 (500) ,
    A997NIVEL          NUMBER
  ) ;
COMMENT ON TABLE SIST_T997_MENSAJE_DEBUG
IS
  'MENSAJES DE DEPURACION DEL SISTEMA' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997CODIGO
IS
  'ID DEL REGISTRO' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997FECHAOPERACION
IS
  'FECHA DE OPERACION' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997USUARIO
IS
  'USUARIO QUE REGISTRA OPERACION' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997PAQUETE
IS
  'PAQUETE ONDE SE GENERA MENSAJE' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997PROCEDIMIENTO
IS
  'PROCEDIMIENTO O FUNCION' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997DESCRIPCION
IS
  'DESCRIPCION DEL MENSAJE' ;
  COMMENT ON COLUMN SIST_T997_MENSAJE_DEBUG.A997NIVEL
IS
  'NIVEL DEL MENSAJE' ;
ALTER TABLE SIST_T997_MENSAJE_DEBUG ADD CONSTRAINT PK_T997 PRIMARY KEY (
A997CODIGO ) ;


CREATE
  TABLE SIST_T998_EXCEPCION
  (
    A998CODIGO              NUMBER NOT NULL ,
    A998FECHAEXCEPCION      DATE ,
    A998USUARIO             NUMBER ,
    A998PAQUETE             VARCHAR2 (100) ,
    A998PROCEDIMIENTO       VARCHAR2 (100) ,
    A998CODERROR            NUMBER ,
    A998MSJERROR            VARCHAR2 (4000) ,
    A998FECHACREACION       DATE ,
    A998FECHAMODIFICACION   DATE ,
    A998USUARIOCREACION     NUMBER ,
    A998USUARIOMODIFICACION NUMBER
  ) ;
COMMENT ON TABLE SIST_T998_EXCEPCION
IS
  'EXCEPCIONES GENERADAS POR EL APLICATIVO' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998CODIGO
IS
  'ID DEL REGISTRO' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998FECHAEXCEPCION
IS
  'FECHA DE GENERACION DE EXCEPCION' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998USUARIO
IS
  'ID DEL USUARIO QUE REALIZA OPERACION' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998PAQUETE
IS
  'NOMBRE DEL PAQUETE DONDE SE GENERO' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998PROCEDIMIENTO
IS
  'PROCEDIMIENTO DONDE SE GENERO' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998CODERROR
IS
  'CODIGO DE ERROR DE LA EXCEPCION' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998MSJERROR
IS
  'MENSAJE DEL ERROR' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998FECHACREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998FECHAMODIFICACION
IS
  'FECHA DE MODIFICACION' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998USUARIOCREACION
IS
  'ID DEL USUARIO CREADOR' ;
  COMMENT ON COLUMN SIST_T998_EXCEPCION.A998USUARIOMODIFICACION
IS
  'ID DEL USUARIO ULTIMA MODIFICACION' ;
ALTER TABLE SIST_T998_EXCEPCION ADD CONSTRAINT PK_T998 PRIMARY KEY ( A998CODIGO
) ;


CREATE
  TABLE SIST_T999_MENSAJE_RESPUESTA
  (
    A999CODIGO              VARCHAR2 (10) NOT NULL ,
    A999MENSAJE             VARCHAR2 (200) ,
    A999ESTADOREGISTRO      CHAR (1) ,
    A999FECHACREACION       DATE ,
    A999FECHAMODIFICACION   DATE ,
    A999USUARIOCREACION     NUMBER ,
    A999USUARIOMODIFICACION NUMBER
  ) ;
ALTER TABLE SIST_T999_MENSAJE_RESPUESTA ADD CONSTRAINT CK_A999ESTADOREGISTRO
CHECK ( A999ESTADOREGISTRO IN ('A', 'I')) ;
COMMENT ON TABLE SIST_T999_MENSAJE_RESPUESTA
IS
  'MENSAJES DE RESPUESTA DEL SISTEMA' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999CODIGO
IS
  'ID DEL REGISTRO' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999MENSAJE
IS
  'MENSAJE DE RESPUESTA' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999ESTADOREGISTRO
IS
  'ESTADO DEL REGISTRO' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999FECHACREACION
IS
  'FECHA DE CREACION' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999FECHAMODIFICACION
IS
  'FECHA DE ULTIMA MODIFICACION' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999USUARIOCREACION
IS
  'USUARIO CREADOR' ;
  COMMENT ON COLUMN SIST_T999_MENSAJE_RESPUESTA.A999USUARIOMODIFICACION
IS
  'ULTIMO USUARIO QUE MODIFICO' ;
ALTER TABLE SIST_T999_MENSAJE_RESPUESTA ADD CONSTRAINT PK_T999 PRIMARY KEY (
A999CODIGO ) ;


ALTER TABLE IVET_T001_ENTIDAD ADD CONSTRAINT FK_T001_T105 FOREIGN KEY (
A001CODDIVIPOLA ) REFERENCES PART_T105_DIVIPOLA ( A105CODIGO ) NOT DEFERRABLE ;

ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT FK_T002_T001 FOREIGN KEY (
A002AUTORIDADAMBIENTAL ) REFERENCES IVET_T001_ENTIDAD ( A001CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT FK_T002_T015 FOREIGN KEY (
A002MENU ) REFERENCES IVET_T015_MENU ( A015CODIGO ) NOT DEFERRABLE ;

ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT FK_T002_T102 FOREIGN KEY (
A002IDTIPODOCUMENTO ) REFERENCES PART_T102_LISTA ( A102CODIGO ) NOT DEFERRABLE
;

ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT FK_T002_T102v1 FOREIGN KEY (
A002TIPOUSUARIO ) REFERENCES PART_T102_LISTA ( A102CODIGO ) NOT DEFERRABLE ;

ALTER TABLE IVET_T002_USUARIO ADD CONSTRAINT FK_T002_T105 FOREIGN KEY (
A002LOCALIZACION ) REFERENCES PART_T105_DIVIPOLA ( A105CODIGO ) NOT DEFERRABLE
;

ALTER TABLE IVET_T003_INVENTARIO ADD CONSTRAINT FK_T003_T001 FOREIGN KEY (
A003IDUSUARIOREGISTRO ) REFERENCES IVET_T001_ENTIDAD ( A001CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T003_INVENTARIO ADD CONSTRAINT FK_T003_T102 FOREIGN KEY (
A003ESTADO_INVENTARIO ) REFERENCES PART_T102_LISTA ( A102CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T003_INVENTARIO ADD CONSTRAINT FK_T003_T105 FOREIGN KEY (
A003IDDIVIPOLA ) REFERENCES PART_T105_DIVIPOLA ( A105CODIGO ) NOT DEFERRABLE ;

ALTER TABLE IVET_T004_GEOMETRIA ADD CONSTRAINT FK_T004_T002 FOREIGN KEY (
A004IDINVENTARIO ) REFERENCES IVET_T002_USUARIO ( A002CODIGO ) NOT DEFERRABLE ;

ALTER TABLE IVET_T007_INVENTARIOFUENTE ADD CONSTRAINT FK_T007_T003 FOREIGN KEY
( A007IDINVENTARIO ) REFERENCES IVET_T003_INVENTARIO ( A003CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T007_INVENTARIOFUENTE ADD CONSTRAINT FK_T007_T006 FOREIGN KEY
( A007IDFUENTE ) REFERENCES IVET_T006_FUENTE ( A006CODIGO ) NOT DEFERRABLE ;

ALTER TABLE IVET_T009_CATEGEMISION ADD CONSTRAINT FK_T009_T003 FOREIGN KEY (
A009IDINVENTARIO ) REFERENCES IVET_T003_INVENTARIO ( A003CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T009_CATEGEMISION ADD CONSTRAINT FK_T009_T008 FOREIGN KEY (
A009IDMETODOEMISION ) REFERENCES IVET_T008_METODOEMISION ( A008CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T009_CATEGEMISION ADD CONSTRAINT FK_T009_T102 FOREIGN KEY (
A009IDTIPOCATEMISION ) REFERENCES PART_T102_LISTA ( A102CODIGO ) NOT DEFERRABLE
;

ALTER TABLE IVET_T009_CATEGEMISION ADD CONSTRAINT FK_T009_T102v1 FOREIGN KEY (
A009IDTIPOCOMBUSTIBLE ) REFERENCES PART_T102_LISTA ( A102CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T010_CATEGCOMBUSTIBLE ADD CONSTRAINT FK_T010_T009 FOREIGN KEY
( A010CODCATEMISION ) REFERENCES IVET_T009_CATEGEMISION ( A009CODIGO )
NOT DEFERRABLE ;

ALTER TABLE IVET_T010_CATEGCOMBUSTIBLE ADD CONSTRAINT FK_T010_T102 FOREIGN KEY
( A010IDTIPOCOMBUSTIBLE ) REFERENCES PART_T102_LISTA ( A102CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T013_CATEGCONTAMINA ADD CONSTRAINT FK_T013_T005 FOREIGN KEY (
A013IDCONTAMINANTE ) REFERENCES IVET_T005_CONTAMINANTE ( A005CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T013_CATEGCONTAMINA ADD CONSTRAINT FK_T013_T009 FOREIGN KEY (
A013IDCATEGORIAEMISION ) REFERENCES IVET_T009_CATEGEMISION ( A009CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T013_CATEGCONTAMINA ADD CONSTRAINT FK_T013_T011 FOREIGN KEY (
A013UNDMEDFACTORACTIV ) REFERENCES IVET_T011_UNIDADMEDIDA ( A011CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T013_CATEGCONTAMINA ADD CONSTRAINT FK_T013_T012 FOREIGN KEY (
A013UNDMEDFACTOREMIS ) REFERENCES IVET_T012_UNIDADMEDIDAFACTOR ( A012CODIGO )
NOT DEFERRABLE ;

ALTER TABLE IVET_T014_ADJUNTO ADD CONSTRAINT FK_T014_T003 FOREIGN KEY (
A014IDINVENTARIO ) REFERENCES IVET_T003_INVENTARIO ( A003CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T016_INVENTCONTAMINA ADD CONSTRAINT FK_T016_T003 FOREIGN KEY (
A016IDINVENTARIO ) REFERENCES IVET_T003_INVENTARIO ( A003CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T016_INVENTCONTAMINA ADD CONSTRAINT FK_T016_T005 FOREIGN KEY (
A016IDCONTAMINANTE ) REFERENCES IVET_T005_CONTAMINANTE ( A005CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T017_CATGEMIS_CIIU ADD CONSTRAINT FK_T017_T009 FOREIGN KEY (
A017CODCATEMISION ) REFERENCES IVET_T009_CATEGEMISION ( A009CODIGO ) NOT
DEFERRABLE ;

ALTER TABLE IVET_T017_CATGEMIS_CIIU ADD CONSTRAINT FK_T017_T108 FOREIGN KEY (
A017IDCODCIIU ) REFERENCES PART_T108_CODIGOCIIU ( A108CODIGO ) NOT DEFERRABLE ;

ALTER TABLE PART_T102_LISTA ADD CONSTRAINT FK_T102_T101 FOREIGN KEY (
A102CATEGORIA ) REFERENCES PART_T101_CATEGORIA ( A101CODIGO ) NOT DEFERRABLE ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            27
-- CREATE INDEX                             0
-- ALTER TABLE                             85
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         27
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
