CREATE OR REPLACE PACKAGE "PK_UTL_CONSTANTE" is

 -- CONSTANTES GENERALES

  NIVEL_SEVERE NUMBER := 1;
  NIVEL_ERROR  NUMBER := 2;
  NIVEL_INFO   NUMBER := 3;
  NIVEL_TRACE  NUMBER := 4;

  ERROR_GENERAL CONSTANT NUMBER := 99999;

  COD_OPERACION_CORRECTA CONSTANT NUMBER := 0;
  MSJ_EXCEPCION_GENERAL  CONSTANT VARCHAR2(100) := 'SE PRESENTO UN ERROR GENERAL EN EL SISTEMA. FAVOR CONTACTAR AL ADMINISTRADOR CON ESTE CODIGO:';

  COD_ACTIVO   CONSTANT CHAR(1) := 'A';
  COD_INACTIVO CONSTANT CHAR(1) := 'I';

  COD_USUARIO_DEFECTO CONSTANT NUMBER := 0;

end PK_UTL_CONSTANTE;
/
CREATE OR REPLACE PACKAGE BODY "PK_UTL_CONSTANTE" is


end PK_UTL_CONSTANTE;
/
